### PR TITLE
Fixed review suggestions

### LINKED ISSUE #18: Fix review suggestions

### PR DESCRIPTION
**Pull request by shreyakurian02**
- Closes #18 
- Fixed review suggestions made in #9, #10, #11, #12, #13, #15

### CODE REVIEW

File: app/javascript/src/components/Dashboard/Contacts/constants.js [hunk 1]
```diff
@@ -4,15 +4,15 @@ import * as yup from "yup";
 import { SINGULAR } from "constants";
 
 export const ROW_DATA = Array.from({ length: 12 }, (_, index) => {
-  const isEven = index % 2 === 0;
+  const isOdd = index % 2;
```
Comment (yedhink) [inline app/javascript/src/components/Dashboard/Contacts/constants.js:7]: The value should be converted to a boolean value for explicitness if you are going with this approach. I preferred the conditional check one that you had before.

**Review by yedhink — COMMENTED** [review]
@shreyakurian02
